services:
  postgres:
    image: postgres:17-alpine
    container_name: sentinelpay-postgres
    environment:
      POSTGRES_DB: sentinelpay
      POSTGRES_USER: sentinelpay
      POSTGRES_PASSWORD: sentinelpay_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinelpay -d sentinelpay"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.14.0
    container_name: sentinelpay-localstack
    environment:
      SERVICES: sqs,sns
    ports:
      - "4566:4566"
    volumes:
      - ./infra/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh:ro


volumes:
  postgres_data:
