spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_SIZE:1}
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:10}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT_MS:5000}
spring.datasource.hikari.validation-timeout=${DB_VALIDATION_TIMEOUT_MS:2000}
spring.flyway.enabled=false

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

sentinelpay.cloud.issuer=${COGNITO_ISSUER_URI}
sentinelpay.cloud.app-client-id=${COGNITO_APP_CLIENT_ID}
sentinelpay.cloud.audience=${COGNITO_API_AUDIENCE}
sentinelpay.sns.payment-events-topic-arn=${PAYMENT_EVENTS_TOPIC_ARN}
sentinelpay.sqs.payment-events-url=${PAYMENT_EVENTS_QUEUE_URL}
sentinelpay.sqs.risk-decisions-url=${RISK_DECISIONS_QUEUE_URL}
sentinelpay.fraud.base-url=${FRAUD_SERVICE_URL}
sentinelpay.fraud.internal-token=${FRAUD_INTERNAL_TOKEN}
sentinelpay.psp.webhook-secret=${PSP_WEBHOOK_SECRET}
sentinelpay.psp.mode=${PSP_MODE:SUCCESS}
