spring.application.name=payments-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sentinelpay}
spring.datasource.username=${DB_USERNAME:sentinelpay}
spring.datasource.password=${DB_PASSWORD:sentinelpay_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

sentinelpay.jwt.secret=sentinelpay-development-secret-key-1234567890

sentinelpay.outbox.poll-ms=1000

sentinelpay.sqs.payment-events-url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/payment-events

