sentinelpay.jwt.secret=${SENTINELPAY_LOCAL_JWT_SECRET}
sentinelpay.psp.mode=AUTO_SUCCESS
sentinelpay.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}
sentinelpay.sns.payment-events-topic-arn=${PAYMENT_EVENTS_TOPIC_ARN:arn:aws:sns:ap-southeast-2:000000000000:payment-events}
